"""initial schema

Baseline migration capturing all 8 memory-store tables in their reconciled
form (the single source of truth is the SQLAlchemy models in
``superseded.memory.models``). This is the revision stamped onto pre-Alembic
databases during auto-adoption.

Accepted pre-existing-DB divergences (not repaired at upgrade time):
- Existing SQLite DBs created before Alembic lack the installation_config
  foreign key (SQLite cannot ALTER TABLE ADD CONSTRAINT; a rebuild is
  disproportionate). Fresh SQLite DBs receive the FK here.
- Existing SQLite findings.comment_id used nominal type INTEGER; BigInteger
  renders as INTEGER on SQLite regardless, so this is affinity-equivalent.

Revision ID: 0001
Revises:
Create Date: 2026-07-07
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('findings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('repo', sa.String(), nullable=True),
    sa.Column('pass', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('file', sa.String(), nullable=True),
    sa.Column('line', sa.Integer(), nullable=True),
    sa.Column('reasoning', sa.String(), server_default='', nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('dismissed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('comment_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('installations',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('app_installation_id', sa.BigInteger(), nullable=False),
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('repos', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_installation_id')
    )
    op.create_table('learned_rules',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('repo', sa.String(), nullable=False),
    sa.Column('rule_text', sa.String(), nullable=False),
    sa.Column('evidence_count', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('confidence', sa.Float(), server_default='1.0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reflection_state',
    sa.Column('repo', sa.String(), nullable=False),
    sa.Column('last_feedback_id', sa.BigInteger(), nullable=False),
    sa.Column('last_reflection_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('repo')
    )
    op.create_table('review_stats',
    sa.Column('repo', sa.String(), nullable=False),
    sa.Column('pass', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('file_pattern', sa.String(), server_default='*', nullable=False),
    sa.Column('total', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('accepted', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('dismissed', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('repo', 'pass', 'severity', 'file_pattern')
    )
    op.create_table('review_watermarks',
    sa.Column('repo', sa.String(), nullable=False),
    sa.Column('pr_number', sa.BigInteger(), nullable=False),
    sa.Column('head_sha', sa.String(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('repo', 'pr_number')
    )
    op.create_table('feedback',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('finding_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('installation_config',
    sa.Column('installation_id', sa.BigInteger(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['installation_id'], ['installations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('installation_id', 'key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('installation_config')
    op.drop_table('feedback')
    op.drop_table('review_watermarks')
    op.drop_table('review_stats')
    op.drop_table('reflection_state')
    op.drop_table('learned_rules')
    op.drop_table('installations')
    op.drop_table('findings')
    # ### end Alembic commands ###
