from __future__ import annotations

import json
import logging

import asyncpg

from superseded.memory._stats_sql import STATS_FILE_PATTERN_CASE

logger = logging.getLogger(__name__)

SCHEMA = """
CREATE TABLE IF NOT EXISTS findings (
    id          TEXT PRIMARY KEY,
    repo        TEXT,
    pass        TEXT,
    severity    TEXT,
    file        TEXT,
    line        INTEGER,
    reasoning   TEXT NOT NULL DEFAULT '',
    title       TEXT,
    description TEXT,
    dismissed   BOOLEAN NOT NULL DEFAULT FALSE,
    comment_id  BIGINT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS feedback (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    finding_id  TEXT REFERENCES findings(id),
    action      TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS installations (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_installation_id BIGINT UNIQUE NOT NULL,
    owner               TEXT NOT NULL,
    repos               TEXT NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS review_watermarks (
    repo        TEXT NOT NULL,
    pr_number   BIGINT NOT NULL,
    head_sha    TEXT NOT NULL,
    reviewed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (repo, pr_number)
);

CREATE TABLE IF NOT EXISTS review_stats (
    repo         TEXT NOT NULL,
    pass         TEXT NOT NULL,
    severity     TEXT NOT NULL,
    file_pattern TEXT NOT NULL DEFAULT '*',
    total        BIGINT NOT NULL DEFAULT 0,
    accepted     BIGINT NOT NULL DEFAULT 0,
    dismissed    BIGINT NOT NULL DEFAULT 0,
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (repo, pass, severity, file_pattern)
);

CREATE TABLE IF NOT EXISTS learned_rules (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    repo            TEXT NOT NULL,
    rule_text       TEXT NOT NULL,
    evidence_count  BIGINT NOT NULL DEFAULT 0,
    confidence      DOUBLE PRECISION NOT NULL DEFAULT 1.0,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_applied_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS reflection_state (
    repo               TEXT NOT NULL,
    last_feedback_id   BIGINT NOT NULL,
    last_reflection_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (repo)
);

CREATE TABLE IF NOT EXISTS installation_config (
    installation_id BIGINT NOT NULL,
    key             TEXT NOT NULL,
    value           TEXT NOT NULL,
    PRIMARY KEY (installation_id, key)
);
"""


def _row_to_dict(row: asyncpg.Record | None) -> dict | None:
    return dict(row) if row is not None else None


class PostgresStore:
    """Postgres-backed implementation of the Store protocol.

    Uses a process-wide asyncpg connection pool created in `open()` and closed
    in `close()`. Every method acquires a connection from the pool. SQL uses
    Postgres-native `$n` placeholders and `ON CONFLICT` upserts.
    """

    def __init__(
        self,
        dsn: str,
        *,
        min_size: int = 1,
        max_size: int | None = None,
    ) -> None:
        self._dsn = dsn
        self._min_size = min_size
        self._max_size = max_size
        self._pool: asyncpg.Pool | None = None

    async def open(self) -> None:
        if self._pool is not None:
            return
        self._pool = await asyncpg.create_pool(
            dsn=self._dsn,
            min_size=self._min_size,
            max_size=self._max_size,
            command_timeout=30,
        )
        assert self._pool is not None
        async with self._pool.acquire() as conn:
            await conn.execute(SCHEMA)
        logger.info("Postgres pool opened (min=%d max=%s)", self._min_size, self._max_size)
        logger.info("Postgres schema ensured")

    async def close(self) -> None:
        if self._pool is not None:
            await self._pool.close()
            self._pool = None

    async def init(self) -> None:
        await self.open()

    async def __aenter__(self) -> PostgresStore:
        await self.open()
        return self

    async def __aexit__(self, *exc: object) -> None:
        # Pool lifecycle is owned by the server lifespan (store.close()); the
        # `async with store:` idiom in the worker only gates a batch of ops,
        # it does not open/close the pool per batch.
        return None

    def _conn(self) -> asyncpg.PoolAcquireContext:
        assert self._pool is not None, "PostgresStore.open() not called"
        return self._pool.acquire()

    async def record_finding(
        self,
        finding_id: str,
        repo: str,
        pass_name: str,
        severity: str,
        file: str,
        line: int,
        title: str,
        description: str,
        reasoning: str = "",
    ) -> None:
        async with self._conn() as conn:
            await conn.execute(
                "INSERT INTO findings "
                "(id, repo, pass, severity, file, line, title, description, reasoning) "
                "VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) "
                "ON CONFLICT(id) DO UPDATE SET "
                "severity = EXCLUDED.severity, "
                "description = EXCLUDED.description, "
                "reasoning = EXCLUDED.reasoning "
                "WHERE EXCLUDED.severity IS DISTINCT FROM findings.severity "
                "OR EXCLUDED.description IS DISTINCT FROM findings.description "
                "OR EXCLUDED.reasoning IS DISTINCT FROM findings.reasoning",
                finding_id,
                repo,
                pass_name,
                severity,
                file,
                line,
                title,
                description,
                reasoning,
            )

    async def set_comment_id(self, finding_id: str, comment_id: int) -> None:
        async with self._conn() as conn:
            await conn.execute(
                "UPDATE findings SET comment_id = $1 WHERE id = $2",
                comment_id,
                finding_id,
            )

    async def get_finding_by_comment_id(self, comment_id: int) -> dict | None:
        async with self._conn() as conn:
            row = await conn.fetchrow("SELECT * FROM findings WHERE comment_id = $1", comment_id)
            return _row_to_dict(row)

    async def record_feedback(self, finding_id: str, action: str) -> None:
        async with self._conn() as conn, conn.transaction():
            await conn.execute(
                "INSERT INTO feedback (finding_id, action) VALUES ($1, $2)",
                finding_id,
                action,
            )
            if action == "dismiss":
                await conn.execute("UPDATE findings SET dismissed = TRUE WHERE id = $1", finding_id)

    async def record_feedback_by_comment_id(self, comment_id: int, action: str) -> bool:
        finding = await self.get_finding_by_comment_id(comment_id)
        if finding is None:
            return False
        await self.record_feedback(finding["id"], action)
        return True

    async def get_dismissed_findings(self, repo: str) -> list[dict]:
        async with self._conn() as conn:
            rows = await conn.fetch(
                "SELECT * FROM findings WHERE repo = $1 AND dismissed = TRUE", repo
            )
            return [dict(r) for r in rows]

    async def record_installation(self, installation_id: int, owner: str, repos: list[str]) -> None:
        async with self._conn() as conn:
            await conn.execute(
                "INSERT INTO installations (app_installation_id, owner, repos) "
                "VALUES ($1, $2, $3) "
                "ON CONFLICT (app_installation_id) DO UPDATE SET "
                "owner = EXCLUDED.owner, repos = EXCLUDED.repos",
                installation_id,
                owner,
                json.dumps(repos),
            )

    async def get_installation(self, installation_id: int) -> dict | None:
        async with self._conn() as conn:
            row = await conn.fetchrow(
                "SELECT * FROM installations WHERE app_installation_id = $1",
                installation_id,
            )
            return _row_to_dict(row)

    async def remove_installation(self, installation_id: int) -> None:
        async with self._conn() as conn:
            await conn.execute(
                "DELETE FROM installations WHERE app_installation_id = $1",
                installation_id,
            )

    async def get_watermark(self, repo: str, pr_number: int) -> str | None:
        async with self._conn() as conn:
            row = await conn.fetchrow(
                "SELECT head_sha FROM review_watermarks WHERE repo = $1 AND pr_number = $2",
                repo,
                pr_number,
            )
            return row["head_sha"] if row is not None else None

    async def set_watermark(self, repo: str, pr_number: int, head_sha: str) -> None:
        async with self._conn() as conn:
            await conn.execute(
                "INSERT INTO review_watermarks (repo, pr_number, head_sha) "
                "VALUES ($1, $2, $3) "
                "ON CONFLICT (repo, pr_number) DO UPDATE SET head_sha = EXCLUDED.head_sha",
                repo,
                pr_number,
                head_sha,
            )

    async def get_learned_rules(self, repo: str, limit: int = 5) -> list[dict]:
        async with self._conn() as conn, conn.transaction():
            rows = await conn.fetch(
                "SELECT * FROM learned_rules "
                "WHERE repo = $1 AND confidence >= 0.3 "
                "ORDER BY confidence DESC, created_at DESC "
                "LIMIT $2",
                repo,
                limit,
            )
            rules = [dict(r) for r in rows]
            if rules:
                ids: list[int] = [r["id"] for r in rules]
                # Build $n placeholders for the IN list (starts at $1: no other params here).
                placeholders = ",".join(f"${i + 1}" for i in range(len(ids)))
                await conn.execute(
                    f"UPDATE learned_rules SET last_applied_at = NOW() "
                    f"WHERE id IN ({placeholders})",
                    *ids,
                )
            return rules

    async def get_reflection_state(self, repo: str) -> int:
        async with self._conn() as conn:
            row = await conn.fetchrow(
                "SELECT last_feedback_id FROM reflection_state WHERE repo = $1", repo
            )
            return row["last_feedback_id"] if row is not None else 0

    async def set_reflection_state(self, repo: str, last_feedback_id: int) -> None:
        async with self._conn() as conn:
            await conn.execute(
                "INSERT INTO reflection_state (repo, last_feedback_id) "
                "VALUES ($1, $2) "
                "ON CONFLICT (repo) DO UPDATE SET last_feedback_id = EXCLUDED.last_feedback_id",
                repo,
                last_feedback_id,
            )

    async def refresh_review_stats(self, repo: str) -> None:
        async with self._conn() as conn:
            await conn.execute(
                f"INSERT INTO review_stats "
                f"(repo, pass, severity, file_pattern, total, accepted, dismissed) "
                f"SELECT f.repo, f.pass, f.severity, "
                f"{STATS_FILE_PATTERN_CASE} AS file_pattern, "
                f"COUNT(*) AS total, "
                f"COUNT(*) FILTER (WHERE fb.action = 'helpful') AS accepted, "
                f"COUNT(*) FILTER (WHERE fb.action = 'dismiss') AS dismissed "
                f"FROM findings f "
                f"JOIN feedback fb ON fb.finding_id = f.id "
                f"WHERE f.repo = $1 "
                f"GROUP BY f.repo, f.pass, f.severity, file_pattern "
                f"ON CONFLICT (repo, pass, severity, file_pattern) DO UPDATE SET "
                f"total = EXCLUDED.total, "
                f"accepted = EXCLUDED.accepted, "
                f"dismissed = EXCLUDED.dismissed, "
                f"updated_at = NOW()",
                repo,
            )

    async def get_review_stats(self, repo: str, min_sample: int) -> list[dict]:
        async with self._conn() as conn:
            rows = await conn.fetch(
                "SELECT * FROM review_stats WHERE repo = $1 AND total >= $2",
                repo,
                min_sample,
            )
            return [dict(r) for r in rows]

    async def get_installation_config(self, installation_id: int) -> dict[str, str]:
        async with self._conn() as conn:
            rows = await conn.fetch(
                "SELECT key, value FROM installation_config WHERE installation_id = $1",
                installation_id,
            )
            return {row["key"]: row["value"] for row in rows}

    async def set_installation_config(self, installation_id: int, key: str, value: str) -> None:
        async with self._conn() as conn:
            await conn.execute(
                "INSERT INTO installation_config (installation_id, key, value) "
                "VALUES ($1, $2, $3) "
                "ON CONFLICT (installation_id, key) DO UPDATE SET value = EXCLUDED.value",
                installation_id,
                key,
                value,
            )

    async def prune_stale_rules(self, repo: str, max_age_days: int = 30) -> int:
        """Delete learned rules not applied within ``max_age_days``."""
        async with self._conn() as conn:
            result = await conn.execute(
                "DELETE FROM learned_rules "
                "WHERE repo = $1 "
                "AND (last_applied_at IS NULL OR "
                "last_applied_at < NOW() - INTERVAL '1 day' * $2)",
                repo,
                max_age_days,
            )
            count = int(result.split()[-1]) if result else 0
            return count

    async def dismiss_learned_rule(self, rule_id: int) -> bool:
        async with self._conn() as conn:
            result = await conn.execute(
                "UPDATE learned_rules SET confidence = confidence * 0.5 WHERE id = $1",
                rule_id,
            )
            count = int(result.split()[-1]) if result else 0
            return count > 0

    async def reinforce_learned_rule(self, rule_id: int) -> bool:
        async with self._conn() as conn:
            result = await conn.execute(
                "UPDATE learned_rules SET confidence = LEAST(1.0, confidence + 0.1) WHERE id = $1",
                rule_id,
            )
            count = int(result.split()[-1]) if result else 0
            return count > 0

    async def get_all_learned_rules(self, repo: str) -> list[dict]:
        async with self._conn() as conn:
            rows = await conn.fetch(
                "SELECT * FROM learned_rules WHERE repo = $1 "
                "ORDER BY confidence DESC, created_at DESC",
                repo,
            )
            return [dict(r) for r in rows]
